### ISSUE TITLE
Where is the doc of the standard properties?

### ISSUE THREAD

**Issue by dmaffitt** [indilib/docs#7]
https://www.indilib.org/developers/deveioper-manual/101-standard-properties.html.  This 404s.

**Comment by knro** [comment]
Where did you find this URL?

**Comment by dmaffitt** [comment]
This is a bookmark I have. I am hoping the equivalent of this page migrated. On Jun 27, 2024, at 1:07 PM, Jasem Mutlaq ***@***.***> wrote:﻿
Where did you find this URL?

**Comment by knro** [comment]
https://www.indilib.org/developers/developer-manual/101-standard-properties.html

This is the correct URL.
